name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Gera todo dia Ã  meia-noite UTC
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependÃªncias
        run: |
          python -m pip install --upgrade pip
          pip install -r <(echo "ghp-import==2.0.1")

      - name: Gerar a Snake
        uses: Platane/snk@master
        with:
          github_user_name: WesleyFilhoDev
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git --work-tree=dist add --all
          git commit -m "Atualizando snake ðŸ"
          git push -f origin output

